# FTR: Configuration on https://travis-ci.org/vector-im/riotX-android/settings
#
# - Build only if .travis.yml is present -> On
# - Limit concurrent jobs                -> Off
# - Build pushed branches                -> On (build the branch)
# - Build pushed pull request            -> On (build the PR after auto-merge)
#
# - Auto cancel branch builds            -> On
# - Auto cancel pull request builds      -> On

language: android
jdk: oraclejdk8
sudo: false

notifications:
  email: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

# Build with the development SDK
before_script:
  # Not necessary for the moment
  # - /bin/sh ./set_debug_env.sh

# Just build the project for now
script:
  # Build app (assembleAppgplayRelease assembleAppfdroidRelease)
  # Build Android test (assembleAndroidTest) (disabled for now)
  # Code quality (lintAppgplayRelease lintAppfdroidRelease)
  - ./gradlew clean assembleAppgplayRelease assembleAppfdroidRelease lintAppgplayRelease lintAppfdroidRelease --stacktrace
  # Run unitary test (Disable for now, see https://travis-ci.org/vector-im/riot-android/builds/502504370)
  # - ./gradlew testAppgplayReleaseUnitTest --stacktrace
  # Other code quality check
  - ./tools/check/check_code_quality.sh
  - ./tools/travis/check_pr.sh
  # Check that indonesians file are identical. Due to Android issue, the resource folder must be value-in/, and Weblate export data into value-id/.
  - diff ./app/src/main/res/values-id/strings.xml ./app/src/main/res/values-in/strings.xml
