[package]
name = "matrix-crypto-bindings"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "matrix_crypto"

[dependencies]
serde_json = "1.0.62"
http = "0.2.3"

thiserror = "1.0.23"
tracing = "0.1.23"
tracing-subscriber = "0.2.15"

[dependencies.js_int]
version = "0.2.0"
features = ["lax_deserialize"]

[dependencies.matrix-sdk-common]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
branch = "encryption-info"

[dependencies.matrix-sdk-crypto]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
branch = "encryption-info"
features = ["sled_cryptostore"]

[dependencies.tokio]
version = "1.2.0"
default_features = false
features = ["rt-multi-thread"]

[dependencies.uniffi]
version = "0.7.0"
git = "https://github.com/mozilla/uniffi-rs"
rev = "f7c8ccda783494ee507ea0f8a61f35b39527394f"

[build-dependencies]
uniffi_build = "0.7.0"
