[package]
name = "matrix-crypto-bindings"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "matrix_crypto"

[dependencies]
matrix-sdk-common = { git = "https://github.com/matrix-org/matrix-rust-sdk/"}

serde_json = "1.0.62"
http = "0.2.3"

thiserror = "1.0.23"
tracing = "0.1.23"
tracing-subscriber = "0.2.15"

[dependencies.matrix-sdk-crypto]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
features = ["sled_cryptostore"]

[dependencies.tokio]
version = "1.2.0"
default_features = false
features = ["rt-multi-thread"]

[dependencies.uniffi]
version = "0.7.0"
git = "https://github.com/mozilla/uniffi-rs"
branch = "tagged-unions"

[build-dependencies]
uniffi_build = "0.7.0"

[patch.crates-io]
olm-sys = { git = "https://gitlab.gnome.org/poljar/olm-sys/", branch = "android-cross" }
