[package]
name = "matrix-crypto-bindings"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "matrix_crypto"

[dependencies]
serde = "1.0.126"
serde_json = "1.0.64"
http = "0.2.4"

thiserror = "1.0.25"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
uniffi = "0.12.0"

[dependencies.js_int]
version = "0.2.0"
features = ["lax_deserialize"]

[dependencies.matrix-sdk-common]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
rev = "0fb3dedd1cd3b0766fa7378754480d52d38e8ef2"

[dependencies.matrix-sdk-crypto]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
rev = "0fb3dedd1cd3b0766fa7378754480d52d38e8ef2"
features = ["sled_cryptostore"]

[dependencies.tokio]
version = "1.6.0"
default_features = false
features = ["rt-multi-thread"]

[dependencies.ruma]
version = "*"
features = ["client-api"]

[build-dependencies]
uniffi_build = "0.12.0"
