[package]
name = "matrix-crypto-bindings"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "matrix_crypto"

[dependencies]
matrix-sdk-crypto = { git = "https://github.com/matrix-org/matrix-rust-sdk/", features = ["sled_cryptostore"] }
matrix-sdk-common = { git = "https://github.com/matrix-org/matrix-rust-sdk/"}
futures = { version = "0.3.12", default_features = false, features = ["executor"] }
tokio = { version = "1.1.1", default_features = false, features = ["rt-multi-thread", "time"] }
serde_json = "1.0.61"
thiserror = "1.0.23"
http = "0.2.3"
uniffi = "0.7.0"

[build-dependencies]
uniffi_build = "0.7.0"

[patch.crates-io]
olm-sys = { git = "https://gitlab.gnome.org/poljar/olm-sys/", branch = "android-cross" }
